--- 
title: 'HarvardX PH125.9x: Movielens project'
author: "Yin-Chi Chan"
date: "`r Sys.Date()`"
documentclass: article
mainfont: Times New Roman
mathfont: Cambria Math
monofont: Cascadia Code
geometry: margin=2.5cm
bibliography: book.bib
biblio-style: acm
description: |
  See also: _output.yml, _bookdown.yml
link-citations: yes
site: bookdown::bookdown_site
---

# Preface {-}

This book is available in both [HTML gitbook](index.html) and [PDF](movielens.pdf) form.

The source code in the PDF version of this report is typeset in
[Cascadia Code](https://github.com/microsoft/cascadia-code), with code ligatures enabled.

## R setup

```{r Setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  dpi = 144
)

def.chunk.hook  <- knitr::knit_hooks$get("chunk")
if (knitr::is_latex_output()) {
  knitr::knit_hooks$set(chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    paste0("\n \\", "small","\n\n", x, "\n\n \\normalsize")
  })
}
```

```{r Load-libraries}

# R 4.1 key features: new pipe operator, \(x) as shortcut for function(x)
# R 4.0 key features: stringsAsFactors = FALSE by default, raw character strings r"()"
if (packageVersion('base') < '4.1.0') {
  stop('This code requires R >= 4.1.0!')
}

if(!require("pacman")) install.packages("pacman")
library(pacman)

# Ensure packages are installed but do not load them
p_install(Rcpp, force = F)
p_install(RcppArmadillo, force = F)
p_install(RcppProgress, force = F)
p_install(mgcv, force = F)          # provides mgcv::gam and mgcv::predict.gam
p_install(raster, force = F)        # provides raster::clamp

# Load these packages
p_load(magrittr, knitr, kableExtra, data.table, latex2exp, patchwork,
       tidyverse, caret, lubridate)
```
